version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony/
    ports:
      - '8001:80'
    networks:
      - symfony
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://user:password@mysql:3306/fruits_db?serverVersion=5.7
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_DATABASE: fruits_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
#    volumes:
#      - ./mysql:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
